/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   FileReaders.h
 * Author: hudaiber
 *
 * Created on January 29, 2016, 1:38 PM
 */
#include <vector>
#include<unordered_map>

using namespace std;

namespace DataIO{
    vector<BioClass::Gene> readWGSFile(string fname);
    //Read bz2 compressed csv files containing kplets generated by pickle2csv.py
    vector<KpletClass::Kplet> readKpletsFromCsvBz2(string fname);
    void readKpletsFromCsvBz2(string fname,
                              vector<KpletClass::Kplet_ind> &kplets,
                              vector<string> &files,
                              unordered_map<string,unsigned int> &file2ind,
                              vector<string> &profiles,
                              unordered_map<string,unsigned int> &profile2ind);
    void readKpletsFromCsv(string fname,
                            vector<KpletClass::Kplet_ind> &kplets,
                            vector<string> &files,
                            unordered_map<string,unsigned int> &file2ind,
                            vector<string> &profiles,
                            unordered_map<string,unsigned int> &profile2ind);
    void readKpletsFromCsv(string fname,
                            vector<KpletClass::Kplet> &kplets);
    void writeMergedListsToCsv(vector<KpletClass::KpletList> &kplet_lists,
                               string fname);
    void writeMergedListsToCsv(vector<KpletClass::KpletList_ind> &kplet_lists,
                               string fname);
}
