/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   FileReaders.h
 * Author: hudaiber
 *
 * Created on January 29, 2016, 1:38 PM
 */
#include <vector>



using namespace std;

namespace FileReader{
    
    vector<BioClass::Gene> readWGSFile(string fname);
    
    //Read bz2 compressed csv files containing kplets generated by pickle2csv.py
    vector<KpletClass::Kplet> readKpletsFromCsvBz2(string fname);
    
    vector<KpletClass::Kplet> readKpletsFromCsv(string fname);
    
}

